### ISSUE TITLE
nextFrameId do not increment

### ISSUE THREAD

**Issue by sergioffpc** [jankolkmeier/xbee-api#20]
The latest updates broke the nextFrameId() function.

The following code always output "0": for (i=0; i<100;++i) console.log(xbee.nextFrameId());

Best Regards,
Sérgio Carvalho

**Comment by jankolkmeier** [comment]
Fixed. Sorry for this!

**Comment by sergioffpc** [comment]
I confirm the correction.

Take this opportunity to congratulate your extraordinary library and thanks for the quick fix.
