### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by beinnova** [jankolkmeier/xbee-api#27]
Hi, 
Firstly complimet for the great job!
Secondoly I have one question for you: it's possible to make some personals frame builder/parser to send data with my personal form?

**Comment by jankolkmeier** [comment]
Thenks for the coplimet.

I'm not sure what you want to achieve. A HTML form? You want to use xbee-api in the backend of your website? You want to make a web interface?

Whatever it is, the answer is probably yes.

**Comment by beinnova** [comment]
I'm sorry, I wrote the last post in a very bad english :smile:  . I mean if it's possible to make personal frame builder for send parsonal frame with personal parameters. Like Digi Sensors.

**Comment by xianlin** [comment]
It is possible. XBee is just a carrier to send your frame content. You can define your own frame with your own parameters. 

One example is Libelium's waspmote, they defined and used their own frame. You can take a look into their manuals for more details.

**Comment by beinnova** [comment]
​
Ok, i have find the solution. Now I can parse my personal frame. Thanks a
lot.


​Regards

Giorgio​

Il giorno mar 21 apr 2015 07:06 xianlin <notifications@github.com> ha
scritto:
