### ISSUE TITLE
Suport Node v4 (and possibly older)

### ISSUE THREAD

**Issue by 101100** [jankolkmeier/xbee-api#53]
The latest version (`0.4.6`) no longer supports Node versions before `v5.10` (when the new `Buffer` API was introduced).  This appears to only be the case due to the use of the new Buffer APIs.

It would be nice if this library supported older versions of Node.js.  This is helpful for small board computers where the latest version is not always available.

The [`safe-buffer`](https://github.com/feross/safe-buffer) library provides access to the new APIs for older version of Node and has no other dependencies.  Would you accept a change to use that?

**Comment by jankolkmeier** [comment]
First of all, sorry if this change caused any inconvenience for you. Maybe this change would've better been denoted by a major version.

Although I prefer to keep as few deps as possible, I think this is a very reasonable change. And I am certainly interested in supporting small boards / IoT devices. 

Will you make a pull request?

**Comment by jankolkmeier** [comment]
Additionally, maybe it would be good to update the Travis unit tests to include multiple versions (before and after 0.4).
