### ISSUE TITLE
Reading Address 64

### ISSUE THREAD

**Issue by Beyondem** [jankolkmeier/xbee-api#56]
So, I see I can read the remote64 from incoming frames of remote devices. What I want to be able to do, is on startup of my application read the remote64 of the xbee I have connected via serial. Is this not possible?I have dug through the api and cant seem to see where I am able to read this parameter.

Is the best way to send both a SL and a SH frame and wait for both replies? Or is there a much easier way?

Can anybody point me in the right direction? Thanks!

**Comment by jankolkmeier** [comment]
AT commands are the only way to query properties from the module. You read the manual right, there are only the SL and SH commands to query the address with, none that replies both in one.
