### ISSUE TITLE
Example's SerialPort version is too old and no response msg when using new version of serialport

### ISSUE THREAD

**Issue by yipsama** [jankolkmeier/xbee-api#64]
In the new version of serialport, the following code
var SerialPort = require('serialport').SerialPort;
should be replaced by var SerialPort = require('serialport');

And after modifying, nodejs does not print out any response after sending "AT" "NI" command.
I was thinking that it is because there is no parser option in serialport now but with "parsers" function.

**Comment by jankolkmeier** [comment]
duplicate of #62 , feel free to provide a PR with for serialport 5 compatibility, or stick to a previous version of serialport for now.
