### ISSUE TITLE
Xbee S2C Digi Mesh protocol support

### ISSUE THREAD

**Issue by bidyutper** [jankolkmeier/xbee-api#67]
Hi Thx for grt library. Does it work while my xbee running in Digimesh firmware. Means can able to get data if I attach xbee coordinator via serial.
RX that I receiving at Xbee Cordinator side from Xbee Router as below
Receive Packet (API 1)

7E 00 18 90 00 13 A2 00 41 55 4B 8C FF FE C2 54 2C 32 35 2C 33 32 37 31 2C 30 0A 48

Start delimiter: 7E

Length: 00 18 (24)

Frame type: 90 (Receive Packet)

64-bit source address: 00 13 A2 00 41 55 4B 8C

16-bit source address: FF FE

Receive options: C2

RF data: 54 2C 32 35 2C 33 32 37 31 2C 30 0A

Checksum: 48

**Comment by jankolkmeier** [comment]
I don't understand your question.
Yes, digimesh / router / coordinator specific frames are supported.
Yes, the specific frame ([0x90](https://github.com/jankolkmeier/xbee-api#0x90-zigbee-receive-packet-ao0-znet-zigbee)) is supported.
